"""Fact test EV-18: Official reference CLI compatibility.

Fact: JAB.REFERENCE.ACCEPTS_ENCODE.v1
Given the example1 plaintext, when this library encodes an image
and the official decoder reads it, then the official decoder returns that plaintext.
"""

from __future__ import annotations

import tempfile
from pathlib import Path

import pytest

import pyhue2d
from pyhue2d.reference import NullReferenceCodec, get_reference_codec
from tests.support.sidecar import load_sidecar


def test_reference_codec_contract_null_adapter():
    """Verify ReferenceCodec port contract using capture-backed null adapter."""
    sidecar = load_sidecar("example1.png.json")
    expected_text = sidecar.input_text.encode("utf-8")
    example1_path = Path("tests/fixtures/approved/jabcode/example1.png")

    null_codec = NullReferenceCodec()
    payload = null_codec.decode(example1_path)
    assert payload == expected_text


def test_reference_cli_accepts_encode():
    """Test official CLI decodes an image generated by pyhue2d.encode (Phase V16)."""
    codec = get_reference_codec()
    if codec is None:
        pytest.skip("Phase V16 blocked: official jabcode binary (LOCAL-DATA-05) is absent")

    sidecar = load_sidecar("example1.png.json")
    expected_payload = sidecar.input_text.encode("utf-8")

    # Encode example1 plaintext using our library
    img = pyhue2d.encode(sidecar.input_text)

    with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as tmp:
        tmp_path = Path(tmp.name)

    try:
        img.save(str(tmp_path), format="PNG")
        decoded_payload = codec.decode(tmp_path)
        assert decoded_payload == expected_payload
    finally:
        if tmp_path.exists():
            tmp_path.unlink()
